### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by dallinski** [bmhayward/Transcode#6]
Hi, I'm admittedly a Mac-newbie and am used to removing apps by simply moving to the trash. How can I uninstall Transcode?

**Comment by bmhayward** [comment]
Thanks for reaching out.

You can download the uninstaller here:

https://github.com/bmhayward/Transcode/blob/master/Transcode/uninstallTranscode.sh

You will need to run it from the Terminal.

If you need anything else, please let me know.

Thanks,
Brent

**Comment by dallinski** [comment]
Thank you! I really like Transcode, but am transitioning to using my always-on server (running Debian) for all of my transcoding purposes.
